Entities/Dtos/QuestionReport/QuestionReportDto.cs
namespace IdealDiscuss.Entities.Dtos.QuestionReport
{
    public class QuestionReportDto
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string QuestionId { get; set; }
        public string QuestionReporter { get; set; }
        public string AdditionalComment { get; set; }
        public string QuestionText { get; set; }
        public List<string> FlagNames { get; set; } = new List<string>();
    }
}

Entities/QuestionReport.cs
namespace IdealDiscuss.Entities
{
    public class QuestionReport : BaseEntity
    {
        public string UserId { get; set; }
        public User User { get; set; }
        public string QuestionId { get; set; } 
        public Question Question { get; set; }
        public string AdditionalComment { get; set; }
        public ICollection<QuestionReportFlag> QuestionReportFlags { get; set; } = new HashSet<QuestionReportFlag>();
    }
}

Models/QuestionReport/CreateQuestionReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace IdealDiscuss.Models.QuestionReport;

public class CreateQuestionReportViewModel
{
    public string UserId { get; set; }
    public string QuestionId { get; set; }

    [Required(ErrorMessage = "One or more flags need to be selected")]
    public List<string> FlagIds { get; set; } = new List<string>();
    [Required(ErrorMessage = " Comment text required")]
    [MinLength(20, ErrorMessage = "Minimum of 20 character required")]
    [MaxLength(150, ErrorMessage = "Maximum of 150 character required")]
    public string AdditionalComment { get; set; }
}

Models/QuestionReport/QuestionReportResponseModel.cs
namespace IdealDiscuss.Models.QuestionReport;

public class QuestionReportResponseModel : BaseResponseModel
{
    public QuestionReportViewModel Data { get; set; }
}

public class QuestionReportsResponseModel : BaseResponseModel
{
    public List<QuestionReportViewModel> Data { get; set; }
}

Models/QuestionReport/QuestionReportViewModel.cs
namespace IdealDiscuss.Models.QuestionReport;

public class QuestionReportViewModel
{
    public string Id { get; set; }
    public string UserId { get; set; }
    public string QuestionId { get; set; }
    public string QuestionReporter { get; set; }
    public string AdditionalComment { get; set; }
    public string QuestionText { get; set; }
    public List<string> FlagNames { get; set; } = new List<string>();
}

Models/QuestionReport/UpdateQuestionReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace IdealDiscuss.Models.QuestionReport;

public class UpdateQuestionReportViewModel
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int QuestionId { get; set; }
    [Required(ErrorMessage = " Comment text required")]
    [MinLength(20, ErrorMessage = "Minimum of 20 character required")]
    [MaxLength(150, ErrorMessage = "Maximum of 150 character required")]
    public string AdditionalComment { get; set; }
}

Controllers/QuestionReportController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using IdealDiscuss.Models.QuestionReport;
using IdealDiscuss.Service.Implementations;
using IdealDiscuss.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace IdealDiscuss.Controllers
{
    public class QuestionReportController : Controller
    {
        private readonly IQuestionReportService _questionReportService;
        private readonly INotyfService _notyf;
        private readonly IFlagService _flagService;

        public QuestionReportController(
            IQuestionReportService questionReportService,
            IFlagService flagService,
            INotyfService notyf)
        {
            _questionReportService = questionReportService;
            _notyf = notyf;
            _flagService = flagService;
        }

        //public IActionResult Index()
        //{
        //    var response = _questionReportService.GetAllQuestionReport();
        //    ViewBag.Message = response.Message;
        //    ViewBag.status = response.Status;

        //    return View(response.Data);
        //}

        //    return RedirectToAction("Index", "QuestionReport");
        //}

        public async Task<IActionResult> ReportQuestion()
        {
            ViewBag.FlagLists = await _flagService.SelectFlags();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ReportQuestion(CreateQuestionReportViewModel Report)
        {
            var response = await _questionReportService.CreateQuestionReport(Report);

            if (response.Status is false)
            {
                return View(response);
            }

            _notyf.Success(response.Message);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> GetQuestionReport(string id)
        {
            var response = await _questionReportService.GetQuestionReport(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);

                return RedirectToAction("Index", "Question");
            }

            return View(response.Data);
        }

        public async Task<IActionResult> GetQuestionReports(string id)
        {
            var response = await _questionReportService.GetQuestionReports(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Question");
            }

            return View(response.Data);
        }

        public async Task<IActionResult> UpdateQuestionReport(string id)
        {
            var response = await _questionReportService.GetQuestionReport(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Question");
            }

            return RedirectToAction("Index", "Question");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateQuestionReport(string id, UpdateQuestionReportViewModel request)
        {
            var response = await _questionReportService.UpdateQuestionReport(id, request);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Question");
            }

            _notyf.Success(response.Message);
            return RedirectToAction("Index", "Question");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteQuestionReport(string id)
        {
            var response = await _questionReportService.DeleteQuestionReport(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Question");
            }

            _notyf.Success(response.Message);

            return RedirectToAction("Index", "Question");
        }
    }
}

Views/QuestionReport/GetQuestionReport.cshtml
@model IdealDiscuss.Models.QuestionReport.QuestionReportViewModel
@{
    ViewData["Title"] = "Question Report Detail";
}

<h3 class="card-title">
    @ViewData["Title"]
</h3>

<div class="card-body">
    <dl class="row">
        <dt class="col-sm-4">AdditionalComment</dt>
        <dd class="col-sm-8">@Model.AdditionalComment</dd>
        <dt class="col-sm-4">FlagNames</dt>
        <dt class="col-sm-8">
            @foreach (var flag in Model.FlagNames)
            {
                <i class="badge bg-dark">@flag</i>
            }
        </dt>
    </dl>

    @* <a class="btn btn-success" asp-action="UpdateQuestionReport" asp-controller="QuestionReport" asp-route-id="@Model.Id">update</a>

    &nbsp;
    <a class="btn btn-primary" asp-action="Index" asp-controller="QuestionReport">Back to List</a>
    &nbsp;
    <hr />
    <form asp-action="DeleteQuestionReport" asp-controller="QuestionReport" asp-route-id="@Model.Id">
    <button type="submit" class="btn btn-danger">Delete</button>
    </form>*@
    <a asp-controller="QuestionReport" asp-action="GetQuestionReports" asp-route-id="@Model.QuestionId" class="btn btn-success">Back</a>
</div>

Views/QuestionReport/GetQuestionReports.cshtml
@model List<IdealDiscuss.Models.QuestionReport.QuestionReportViewModel>

@{
    ViewData["Title"] = "View Question Reports";
    var count = 1;
}

@if (Model is not null)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Flag</th>
                <th scope="col">Reporter</th>
                <th scope="col">Action</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td scope="row">@count</td>
                    <td scope="row">
                        @foreach(var flag in item.FlagNames)
                        {
                            <i class="badge bg-black">@flag</i>
                        }
                    </td>
                    <td scope="row">@item.QuestionReporter</td>

                    <td scope="row">
                        <a asp-controller="QuestionReport" asp-action="GetQuestionReport" asp-route-id="@item.Id">View Report Detail</a>
                    </td>
                </tr>
                count++;
            }
        </tbody>
    </table>

    <div>
        <a asp-controller="Question" asp-action="Index" class="btn btn-secondary">
            Back
        </a>
    </div>
}

Views/QuestionReport/Index.cshtml
@model List<IdealDiscuss.Models.QuestionReport.QuestionReportViewModel>
@{
    ViewData["Title"] = "Report List";
    int count = 1;
    var status = ViewBag.Status == false ? false : true;
}

 @await Html.PartialAsync("_ListAlert", Model)

@if (status is false)
{
    <span>@ViewBag.Message</span>
    return;
}
<table class="table">
     <thead>
          <tr>
               <th scope="col">#</th>
               <th scope="col">AdditionalComment</th>
               <th scope="col">Action</th>
          </tr>
     </thead>

     <tbody>

        @foreach (var item in Model)
        {
              <tr>
                   <th scope="row">@count</th>
                   <td>@item.AdditionalComment</td>
                   <td>
                        <div class="btn-group">
                             <a asp-controller="QuestionReport" asp-action="GetQuestionReport" asp-route-id="@item.Id" class="btn btn-primary">View Reports</a>
                        </div>
                   </td>
              </tr>
            count++;
        }
     </tbody>
</table>

Views/QuestionReport/ReportQuestion.cshtml
@model IdealDiscuss.Models.QuestionReport.CreateQuestionReportViewModel
@{
    ViewData["Title"] = "Create New Question Report";
    var questionId = ViewContext.RouteData.Values["id"];
}

@section Styles {
    @{
        await Html.RenderPartialAsync("_Select2CssPartial");
    }
}

<div class="body">

    <div class="row">
        <div class="col-md-6">
            <form asp-action="ReportQuestion" asp-controller="QuestionReport">
                <input type="hidden" class="form-control" name="QuestionId" value="@questionId" />

                <div class="col-md-12 mb-3">
                    <select type="checkbox" class="form-control" multiple="multiple"
                            name="FlagIds" required="required"
                            data-placeholder="Select Question Flags"
                            asp-items="@ViewBag.FlagLists">
                    </select>
                </div>

                <div class="col-md-12 mb-3">
                    <label asp-for="AdditionalComment" class="control-label"></label>
                    <textarea asp-for="AdditionalComment" class="form-control"></textarea>
                    <span asp-validation-for="AdditionalComment" class="text-danger"></span>
                </div>

                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Report Question</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_Select2JsPartial");
    }
}

Views/QuestionReport/UpdateQuestionReport.cshtml
@model IdealDiscuss.Models.QuestionReport.QuestionReportViewModel
@{
	ViewData["Title"] = "Update QuestionReport";
}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
		   <form asp-action="Update">

				<div class="form-group"> 
					<label asp-for="AdditionalComment" class="control-label"></label>
						 <input asp-for="AdditionalComment" type="text" class="form-control" value="@Model.AdditionalComment" /><br />
						 <span asp-validation-for="AdditionalComment" class="text-danger"></span>
				</div>
			 <div class="col-md-12">
				 <button type="submit" class="btn btn-primary">Update</button>
			 </div>
			</form>
		</div>
	</div>
</div>